name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
            - name: SecureStack Secrets Analysis
  # You may pin to the exact commit or the version.
  # uses: SecureStackCo/actions-secrets@68f5dca939e2bf6b627449bd5c00f1bb423b01ca
  uses: SecureStackCo/actions-secrets@v0.1.3
  with:
    # SecureStack API key - generate one at https://app.securestack.com
    securestack_api_key: 
    # SecureStack Application ID - available when viewing applications at https://app.securestack.com
    securestack_app_id: 
    # Severities lower than this input value will not be reported; value should be one of: critical | high | medium | low
    severity: 
    # Optional flags for the bloodhound-cli secrets command - run bloodhound-cli code --help for more details.
    flags: # optional, default is 
          
